.\" Manpage for golf.sh
.\" Report errors to https://github.com/gretzky/golf
.TH golf.sh 6 "21 Jun 2018" 0.1.1" "golf.sh man page"

.SH NAME
golf.sh \- a faster way to init a project

.SH DESCRIPTION
a shell dialog program that generates common files needed for most projects based on user input

.SH LINKS
.UR https://github.com/gretzky/golf
\fBRepository\fR
.UE

.SH BUGS
Report any bugs or feature requests to the
.UR https://github.com/gretzky/golf/issues
tracker
.UE

.SH AUTHORS
.UR https://github.com/gretzky
Sara Federico
.UE .

.SH COPYRIGHT
Copyright (c) 2018 Sara Federico

\fIgolf.sh\fR is licensed under the MIT license, see LICENSE file.